app/models/SourceRel.php
<?php

/**
 * This is the model class for table "tb_source_rel".
 *
 * The followings are the available columns in table 'tb_source_rel':
 * @property string $cx
 * @property string $rx
 * @property string $title
 * @property string $ndc
 * @property string $subtitle
 */
class SourceRel extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tb_source_rel';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('cx, rx', 'length', 'max'=>10),
			array('title', 'length', 'max'=>100),
			array('ndc', 'length', 'max'=>20),
			array('subtitle', 'length', 'max'=>7),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('cx, rx, title, ndc, subtitle', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'cx' => 'Cx',
			'rx' => 'Rx',
			'title' => 'Title',
			'ndc' => 'Ndc',
			'subtitle' => 'Subtitle',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('cx',$this->cx,true);
		$criteria->compare('rx',$this->rx,true);
		$criteria->compare('title',$this->title,true);
		$criteria->compare('ndc',$this->ndc,true);
		$criteria->compare('subtitle',$this->subtitle,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return SourceRel the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

app/controllers/SiteController.php
<?php

class SiteController extends Controller {

    public function filters() {
        return array(
            array(
                'COutputCache',
                'duration' => Yii::app()->params['page_cache_duration'],
                'varyByRoute' => true,
                'varyByParam' => array('SourceRel_page', 'page'),
            ),
        );
    }

    public function actionTask1() {
        $criteria = new \CDbCriteria();
        $criteria->addCondition('t.subtitle = \'title 1\'');

        $activeDataProvider = new CActiveDataProvider(
            SourceRel::model()->cache(Yii::app()->params['db_cache_duration']),
            array(
                'criteria' => $criteria,
                'pagination' => array(
                    'pageSize' => 1000
                )
            )
        );

        $this->render('task1', array('activeDataProvider' => $activeDataProvider));
    }

    public function actionTask2() {

        $query = Yii::app()->getDb()->cache(Yii::app()->params['db_cache_duration'])->createCommand()
            ->select('(@id := @id + 1) AS id, cx, rx, title, ndc')
            ->from('tb_source_rel')
            ->join('(SELECT @id := 0) tb', '1=1')
            ->where('subtitle = \'title 1\'')
            ->getText();

        $count = Yii::app()->getDb()->cache(Yii::app()->params['db_cache_duration'])->createCommand()
            ->select('COUNT(cx)')
            ->from('tb_source_rel')
            ->where('subtitle = \'title 1\'')
            ->queryScalar();

        $sqlDataProvider = new CSqlDataProvider(
            $query,
            array(
                'totalItemCount' => $count,
                'pagination' => array(
                    'pageSize' => 1000,
                )
            )
        );


        $this->render('task2', array('sqlDataProvider' => $sqlDataProvider));


    }

    /**
     * This is the action to handle external exceptions.
     */
    public function actionError() {
        if ($error = Yii::app()->errorHandler->error) {
            if (Yii::app()->request->isAjaxRequest) {
                echo $error['message'];
            } else {
                $this->render('error', $error);
            }
        }
    }

}

app/views/layouts/main.php
<!doctype html>
<html>
<head>
    <? include 'parts/_head.php' ?>
</head>
<body>


<body>
<? include 'parts/_nav.php' ?>

<!-- Wrap all page content here -->
<div id="wrap">

    <!-- Fixed navbar -->


    <!-- Begin page content -->
    <div class="container">
        <? include 'parts/_body.php'; ?>
    </div>
</div>
<? include 'parts/_footer.php' ?>


</body>
</html>

app/views/layouts/parts/_body.php
<?= $content; ?>

app/views/layouts/parts/_footer.php
<div id="footer">
    <div class="container">
        <p class="text-muted credit">
        </p>
    </div>
</div>

app/views/layouts/parts/_head.php
<meta charset="utf-8">
<title><?= CHtml::encode($this->pageTitle) ?></title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<?
/** @var ClientScript $clientScript */
$clientScript = Yii::app()->getClientScript();

$baseUrl = Yii::app()->getBaseUrl();
$baseUrlA = Yii::app()->getBaseUrl(true);


$clientScript->registerCoreScript('jquery');
Yii::app()->bootstrap->register();

$clientScript->registerCSSFile($baseUrl . '/css/project.css');
?>

app/views/layouts/parts/_nav.php
<?php $this->widget(
    'bootstrap.widgets.TbNavbar',
    array(
        'brandLabel' => Yii::app()->name,
        'fluid' => false,
        'display' => TbHtml::NAVBAR_DISPLAY_FIXEDTOP,
        'items' => array(
            array(
                'class' => 'bootstrap.widgets.TbNav',
                'items' => array(
                    array('label' => 'Task 1', 'url' => Yii::app()->createUrl('/site/task1'), 'active' => Yii::app()->controller->action->id == 'task1'),
                    array('label' => 'Task 2', 'url' => Yii::app()->createUrl('/site/task2'), 'active' => Yii::app()->controller->action->id == 'task2'),
                ),
            ),
            array(
                'class' => 'bootstrap.widgets.TbNav',
                'htmlOptions' => array('class' => 'pull-right'),
                'items' => array(
                ),
            ),
        ),
    )
);

app/views/site/error.php
<?php
$this->breadcrumbs = array(
    'Ошибка ' . $code
);

$this->pageTitle = 'Ошибка ' . $code;
?>


<div class="page-header">
    <H1>Произошла ошибка</H1>
</div>
<p class="lead">
    <?= \CHtml::encode($message); ?>
</p>

app/views/site/task1.php
<?php

/**
 * @var SiteController $this
 * @var CActiveDataProvider $activeDataProvider
 */

?>

<h2>Task 1</h2>
<p></p>
<?php

$this->widget('bootstrap.widgets.TbGridView', array(
   'id' => 'source-grid',
    'dataProvider' => $activeDataProvider,
    'type' => 'striped bordered hover',
    'enableSorting' => false,
    'columns' => array(
        array(
            'header'=>'#',
            'value'=>'$this->grid->dataProvider->pagination->currentPage * $this->grid->dataProvider->pagination->pageSize + ($row+1)',
        ),
        array(
            'name' => 'cx'
        ),
        array(
            'name' => 'rx'
        ),
        array(
            'name' => 'title'
        ),
        array(
            'name' => 'ndc'
        ),
    )

));
?>

app/views/site/task2.php
<?php

/**
 * @var SiteController $this
 * @var CSqlDataProvider $sqlDataProvider
 */

?>

<h2>Task 2</h2>
<p></p>
<?php

$this->widget('bootstrap.widgets.TbGridView', array(
   'id' => 'source-grid',
    'dataProvider' => $sqlDataProvider,
    'type' => 'striped bordered hover',
    'enableSorting' => false,
    'columns' => array(
        array(
            'header'=>'#',
            'value'=>'$this->grid->dataProvider->pagination->currentPage * $this->grid->dataProvider->pagination->pageSize + ($row+1)',
        ),
        array(
            'name' => 'cx'
        ),
        array(
            'name' => 'rx'
        ),
        array(
            'name' => 'title'
        ),
        array(
            'name' => 'ndc'
        ),
    )

));
?>